Repository microcks/hub.microcks.io, pull requests merged in 2025-02, with the labels that each got.

#96 docs: add missing INSTALLATION.md file for local setup
  INSTALLATION.md
Labels: kind/enhancement, component/documentation

#89 Fix: Updated Broken Privacy Policy Link in Footer
  frontend/src/app/components/footer-bar/footer-bar.component.html
Labels: kind/bug, component/ux

#85 Fix: Updated broken link in Jump Start with Microcks
  frontend/src/app/components/footer-bar/footer-bar.component.html
Labels: kind/bug, component/ux

#106 FIx 104: Image is not Loading
  server/documentation/create-api-mocks.md
Labels: kind/bug, component/documentation
