Repository microcks/hub.microcks.io, pull requests merged in 2025-06, with the labels that each got.

#149 Refactor React project structure for maintainability and testability
  react/index.html
  react/package-lock.json
  react/package.json
  react/src/App.tsx
  react/src/App/App.tsx
  react/src/App/AppHTMLElement.tsx
  react/src/App/Layout/Layout.tsx
  react/src/App/Routing/BrowserRouter.tsx
  react/src/App/Routing/appRoutes.ts
  react/src/App/Routing/routes.tsx
  react/src/assets/css/index.css
  react/src/assets/css/index.ts
  react/src/components/Header.tsx
  react/src/components/HubSection.tsx
  react/src/main.ts
  react/src/main.tsx
  react/src/pages/APIVersion/APIVersion.tsx
  react/src/pages/APIVersion/route.tsx
  react/src/pages/Doc.tsx
  react/src/pages/Doc/Doc.tsx
  react/src/pages/Doc/route.tsx
  react/src/pages/Home/Home.tsx
  react/src/pages/Home/route.tsx
  react/src/pages/Package.tsx
  react/src/pages/Package/Package.tsx
  react/src/pages/Package/route.tsx
Labels: kind/enhancement, component/ux, kind/task

#152 Enhance and Enforce keyboard navigation for A11Y purpose
  react/src/components/Footer.tsx
  react/src/components/Header.tsx
  react/src/components/HubSection.tsx
Labels: component/ux, kind/task

#150 Migrate build tool from Vite to Rsbuild for improved performance and flexibility
  react/package-lock.json
  react/package.json
  react/postcss.config.js
  react/rsbuild.config.ts
  react/src/react-app-env.d.ts
  react/src/vite-env.d.ts
  react/tsconfig.app.json
  react/tsconfig.json
  react/tsconfig.node.json
  react/vite.config.ts
Labels: kind/enhancement, component/build
